Repository MaxCunningham19/legal_spellcheck, pull requests merged in 2023-02, with the labels that each got.

#1 Setup Project File Structure
  client/.gitignore
  client/REACT_README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.js
  server/manage.py
  server/server/__init__.py
  server/server/asgi.py
  server/server/settings.py
  server/server/urls.py
  server/server/wsgi.py
Labels: infrastructure change

#2 Added resource dir for early fe design.
  resources/README_content.md
  resources/fe/design_outline.md
  resources/fe/palette.md
  resources/fe/sketches/prototype.md
  resources/fe/sketches/src/Create_1_static.png
  resources/fe/sketches/src/Create_2_selected.png
  resources/fe/sketches/src/Create_3_validation.png
  resources/fe/sketches/src/Create_4_validate-all.png
  resources/fe/sketches/src/Upload_1_static.png
  resources/fe/sketches/src/colour-palette.png
  resources/fe/sketches/src/demo_layout.mp4
Labels: documentation

#33 Create Action to Test
  .github/workflows/pytest_main.yml
  server/servers_test.py
Labels: infrastructure change

#36 Added yml file to CD to docker hub on creation of a tag
  .github/workflows/docker_cd.yml
Labels: infrastructure change

#34 Chinaza/improve local workflow
  docker/Dockerfile
  docker/README.md
  docker/docker-compose.yml
  scripts/install.sh
  scripts/on-change.sh
  scripts/run-local.bash
  scripts/run-production.bash
  scripts/shell.sh
Labels: infrastructure change

#37 Built app structure and early stateless components.
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.module.css
  client/src/components/Button.js
  client/src/components/Button.module.css
  client/src/components/Editor.js
  client/src/components/Editor.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/Navbar.js
  client/src/components/Navbar.module.css
  client/src/index.js
  client/src/index.module.css
Labels: feature, Frontend

#39 Implemented document area with dynamic input
  client/src/App.module.css
  client/src/components/Carousel.js
  client/src/components/Carousel.module.css
  client/src/components/Editor.js
  client/src/components/Editor.module.css
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/hooks/useAutosizeTextArea.js
  client/src/index.module.css
Labels: bug, feature, help wanted, Frontend

#38 Sprint1: REST API
  api/__init__.py
  api/admin.py
  api/apps.py
  api/generics.py
  api/migrations/0001_initial.py
  api/migrations/__init__.py
  api/models.py
  api/serializers.py
  api/tests.py
  api/views.py
  docker/Dockerfile
  docker/README.md
  docker/docker-compose.yml
  scripts/install.sh
  scripts/managerc.py
  scripts/set-postgres-host.sh
  server/admin.py
  server/apps.py
  server/settings.py
  server/urls.py
Labels: feature, Backend

#44 Bug: Carousel TextBox autoresize
  client/src/components/Carousel.module.css
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/hooks/useAutosizeTextArea.js
Labels: bug, help wanted, Frontend

#42 Added some buttons to front end
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.module.css
  client/src/components/Button.js
  client/src/components/Button.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/Navbar.js
  client/src/index.module.css
  package-lock.json
  package.json
Labels: feature, Frontend

#46 Minor layout fixes and restyling.
  client/src/components/Button.module.css
  client/src/components/TextBox.module.css
  client/src/index.module.css
Labels: simple fix, Frontend

#49 Sprint 2: Updated Carousel to dynamically add/remove paragraphs
  client/src/components/Button.js
  client/src/components/Button.module.css
  client/src/components/Carousel.js
  client/src/components/Carousel.module.css
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/icons/close.svg
  client/src/icons/plus.svg
  client/src/index.module.css
Labels: feature, Frontend

#58 Created buttons in navbar and "saved" message
  client/src/components/Button.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/Navbar.js
  client/src/components/Navbar.module.css
Labels: feature, Frontend

#65 Chinaza/integrate frontend and backend
  client/babel.config.json
  client/package.json
  client/templates/client/app.html
  client/urls.py
  client/views.py
  client/webpack.config.js
  server/settings.py
  server/urls.py
Labels: infrastructure change, Backend, Frontend

#64 Review navbar buttons and header toggle
  client/src/components/Button.js
  client/src/components/Button.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/Navbar.js
  client/src/components/Navbar.module.css
  client/src/icons/file.svg
  client/src/icons/folder-open.svg
  client/src/index.module.css
Labels: feature, Frontend, Sprint 2

#68 Sprint 2: Add links to the items on the menu side bar
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.module.css
  client/src/components/IconExplorer.js
  client/src/components/IconExplorer.module.css
  client/src/components/Navbar.js
  client/src/components/Navbar.module.css
  client/src/index.js
  client/src/index.module.css
  client/src/pages/Browse.js
  client/src/pages/Browse.module.css
  client/src/pages/MyDocuments.js
  client/src/pages/MyDocuments.module.css
Labels: feature, infrastructure change, Frontend, Sprint 2

#70 Sprint 2: Create My Documents page
  client/src/App.module.css
  client/src/components/Button.module.css
  client/src/components/Carousel.js
  client/src/components/Carousel.module.css
  client/src/components/Editor.js
  client/src/components/Explorer.js
  client/src/components/Explorer.module.css
  client/src/components/ExplorerPreview.js
  client/src/components/ExplorerPreview.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/IconExplorer.js
  client/src/components/IconExplorer.module.css
  client/src/components/PreviewIcon.js
  client/src/components/PreviewIcon.module.css
  client/src/components/TextBox.js
  client/src/data/documentsData.json
  client/src/pages/Browse.js
  client/src/pages/MyDocuments.js
  client/src/pages/MyDocuments.module.css
Labels: feature, Frontend, Sprint 2
