Repository MaxCunningham19/legal_spellcheck, pull requests merged in 2023-03, with the labels that each got.

#73 Sprint 2: Browse My Documents section
  client/src/App.module.css
  client/src/components/Carousel.js
  client/src/components/Editor.js
  client/src/components/Explorer.js
  client/src/components/ExplorerPreview.js
  client/src/components/Header.js
  client/src/components/PreviewIcon.js
  client/src/components/PreviewIcon.module.css
  client/src/data/mockAPI.json
  client/src/hooks/useIsMount.js
  client/src/pages/Browse.js
  client/src/pages/MyDocuments.js
  client/src/pages/MyDocuments.module.css
  package-lock.json
  package.json
  static/client/js/main.js
Labels: feature, Frontend, Sprint 2

#79 Added new highlight option
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Carousel.js
  client/src/components/Editor.js
  client/src/components/Header.js
  client/src/components/MistakeHighlighter.js
  client/src/components/MistakeHighlighter.module.css
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/index.module.css
  client/src/pages/Browse.js
  client/src/pages/MyDocuments.js
  package-lock.json
  package.json
  static/client/js/main.js
  test.sh
Labels: feature, Frontend, Sprint 2

#86 Added unique pair constraint to model
  .gitignore
  api/migrations/0004_alter_block_unique_together.py
  api/models.py
  test.sh
Labels: feature, infrastructure change, Backend

#88 Chinaza/bundle in docker for cd workflow
  .github/workflows/docker_cd.yml
  docker/Dockerfile
  docker/docker-compose.yml
Labels: infrastructure change, Sprint 2

#92 Massimiliano/implement history navigation
  client/src/App.js
  client/src/components/Button.module.css
  client/src/components/Editor.js
  client/src/components/Explorer.js
  client/src/components/ExplorerPreview.js
  client/src/components/Navbar.js
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/data/documentsData.json
  client/src/hooks/useDidMount.js
  client/src/icons/save.svg
  client/src/icons/validate-filled.svg
  client/src/icons/validate-outline.svg
  client/src/pages/Browse.js
  client/src/pages/EditorPage.js
  client/src/pages/EditorPage.module.css
  client/src/pages/MyDocuments.js
Labels: feature, Frontend, Sprint 3

#98 Massimiliano / Frontend and backend integration
  .gitignore
  client/src/components/Carousel.js
  client/src/components/Explorer.js
  client/src/components/ExplorerPreview.js
  client/src/components/ExplorerPreview.module.css
  client/src/components/Navbar.js
  client/src/components/Navbar.module.css
  client/src/components/PreviewIcon.js
  client/src/data/mockAPI.json
  client/src/data/mockAPIpost.json
  client/src/icons/validate-outline.svg
  client/src/index.module.css
  client/src/pages/EditorPage.js
  client/src/pages/MyDocuments.js
Labels: infrastructure change, Frontend, Sprint 2, Sprint 3

#105 Massimiliano / Enable POST new documents and PUT titles
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Carousel.js
  client/src/components/Editor.js
  client/src/components/Explorer.js
  client/src/components/ExplorerPreview.js
  client/src/components/ExplorerPreview.module.css
  client/src/components/Header.js
  client/src/components/Header.module.css
  client/src/components/Navbar.js
  client/src/components/PreviewIcon.js
  client/src/components/PreviewIcon.module.css
  client/src/components/TextBox.js
  client/src/components/TextBox.module.css
  client/src/hooks/DocumentContext.js
  client/src/index.js
  client/src/pages/EditorPage.js
  client/src/pages/MyDocuments.js
Labels: feature, infrastructure change, Frontend, Sprint 3

#108 Use regex to match client paths
  server/urls.py
Labels: bug, feature, Backend

#106 Fix bug associated with pushing to empty document
  api/tests.py
  api/views.py
Labels: bug, Backend

#109 Chinaza/add missing document put endpoint
  api/serializers.py
  api/tests.py
  api/views.py
  scripts/managerc.py
Labels: feature, Backend, Frontend

#113 Regex Bug Fix
  server/urls.py
Labels: bug, Backend
